trigger:
- '*'
steps:
- task: DotNetCoreInstaller@0
  inputs:
   version: "2.1.300"
- task: DotNetCoreCLI@2
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  inputs:
    command: build
- task: DotNetCoreCLI@2
  inputs:
    command: test
#This is a comment
