trigger:
- '*'
steps:
- task: DotNetCoreInstaller@0
  inputs:
   version: "2.1.301"
- task: DotNetCoreCLI@2
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  inputs:
    command: build
- task: DotNetCoreCLI@2
  inputs:
    command: test
    nobuild: true
    projects: azurefunctionscicd.test/azurefunctionscicd.test.csproj
