trigger:
- '*'
steps:
- task: DotNetCoreInstaller@0
- task: DotNetCoreCLI@2
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  inputs:
    command: build

# - task: NuGetCommand@2
# - task: MSBuild@1
#   displayName: Build
# - task: DotNetCoreCLI@2
#   displayName: Unit test
#   inputs:
#     command: test
