trigger:
- '*'
steps:
- task: DotNetCoreCLI@2
  displayName: Get dependencies
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
- task: DotNetCoreCLI@2
  displayName: Unit test
  inputs:
    command: test
