trigger:
- '*'
steps:
- task: DotNetCoreInstaller@0
  displayName: Install DotNet Core 2.1.301
  inputs:
   version: "2.1.301"
- task: DotNetCoreCLI@2
  displayName: Restore dependencies
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  displayName: Build function
  inputs:
    command: build
- task: DotNetCoreCLI@2
  displayName: Test functions
  inputs:
    command: test
    nobuild: true
    projects: azurefunctionscicd.test/azurefunctionscicd.test.csproj
- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: happopei-azure
    appType: functionApp
    resourceGroupName:  development
